<?php

/**
 * @file
 * Contains os2forms_form_login.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_help().
 */
function os2forms_form_login_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the os2forms_form_login module.
    case 'help.page.os2forms_form_login':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('OS2Forms Form login') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_webform_third_party_settings_form_alter().
 */
function os2forms_form_login_webform_third_party_settings_form_alter(&$form, FormStateInterface $form_state) {
  Drupal::service('os2forms_form_login.webform_helper')->thirdPartySettingsFormAlter($form, $form_state);
}

/**
 * Implements hook_webform_submission_form_alter().
 */
function os2forms_form_login_webform_submission_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  Drupal::service('os2forms_form_login.webform_helper')->submissionFormAlter($form, $form_state, $form_id);
}

/**
 * Implements hook_user_logout().
 */
function os2forms_form_login_user_logout(AccountInterface $account) {
  Drupal::service('os2forms_form_login.login_provider_helper')->userLogout($account);
}
